const fs = require('fs');
const path = require('path');

const baseDir = './html';
const baseUrl = 'https://www.teyzeevisas.com/html/';

const scanDirectory = (dir, prefix = '') => {
    const items = fs.readdirSync(dir, { withFileTypes: true });
    let result = [];

    for (const item of items) {
        const fullPath = path.join(dir, item.name);
        const relativePath = path.join(prefix, item.name);
        if (item.isDirectory()) {
            result = result.concat(scanDirectory(fullPath, relativePath));
        } else if (item.isFile() && item.name.endsWith('.html')) {
            result.push(relativePath.replace(/\\/g, '/'));
        }
    }

    return result;
};

const files = scanDirectory(baseDir);
let html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Sitemap</title></head>
<body><h1>Sitemap</h1>\n<ul>\n`;

files.forEach(file => {
    const label = path.basename(file, '.html').replace(/-/g, ' ');
    html += <li><a href="${baseUrl}${file}">${label}</a></li>\n;
});

html += '</ul>\n</body></html>';

fs.writeFileSync('./html/sitemap.html', html);
console.log('sitemap.html generated.');
