name: Generate Sitemap

on:
  push:
    paths:
      - 'TeyZee_Visa-main-7/html/**'
      - 'TeyZee_Visa-main-7/scripts/generate_sitemap.py'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate sitemap
        run: |
          python TeyZee_Visa-main-7/scripts/generate_sitemap.py

      - name: Commit sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add TeyZee_Visa-main-7/html/sitemap.html
          git commit -m "Update sitemap.html" || echo "No changes to commit"
          git push
